### ISSUE TITLE
Improve code readability

### ISSUE THREAD

**Issue by romavini** [mdcdxcvi/Spider_Arena#3]
Format the code using an auto formatter or lint (if possible add a github action).

**Comment by brnomendes** [comment]
Suggestion for those who want to contribute to this issue:
 - Use https://github.com/google/google-java-format:
   - Download the formatter and run it in the source code of this repository.
 - Add the https://github.com/marketplace/actions/google-java-format:
   - Create the `.github/workflows/google-java-format.yml ` in the repository and place the settings for this Github Action.
