### ISSUE TITLE
Add a management and builder tool to the project

### ISSUE THREAD

**Issue by romavini** [mdcdxcvi/Spider_Arena#5]
Sugestions: ant, maven or gradle.

**Comment by marcodenisi** [comment]
Hi, can I work on this?

**Comment by alejandrocq** [comment]
I can do this. I will add maven ;)

**Comment by EEM86** [comment]
@mdcdxcvi, hello, I'm wondering why don't you close this task? Maybe you want also add gradle to the project?

**Comment by romavini** [comment]
Oh, thanks @EEM86 for the reminder! I'm closing this issue.
